# This is a basic workflow to help you get started with Actions

name: Submission Timestamp

# Controls when the action will run. 
on:
  push:
    tags:
    - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Add date
        run: |
          TZ="America/Boise" date > .commitdate
          git config --global user.name 'TimestampBot'
          git config --global user.email timestampbot@users.noreply.github.com
          git add .commitdate
          git commit -m 'Adding commit date'
          TAG=$(git tag)
          git tag --force ${TAG}
          git push --force origin ${TAG}
